version: '3.8'

services:
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    depends_on:
      - redis
    volumes:
      - ./backend:/app
    command: ["wait-for-redis.sh", "redis", "npm", "start"]

  frontend:
    build:
      context: ./frontend # Assuming your Vite React app is in ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
